/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: BlockContent;
  author?: AuthorReference;
  categories?: Array<string>;
  publishedAt?: string;
  featured?: boolean;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type WorkExperience = {
  _id: string;
  _type: "workExperience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  title?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  location?: string;
  startDate?: string;
  endDate?: string;
  description?: BlockContent;
  url?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: BlockContent;
  startDate?: string;
  endDate?: string;
  technologies?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: string;
  links?: Array<{
    title?: string;
    url?: string;
    type?: string;
    _key: string;
  }>;
  slug?: Slug;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  longDescription?: BlockContent;
  demoUrl?: string;
  featured?: boolean;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  school?: string;
  degree?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  startDate?: string;
  endDate?: string;
  url?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  initials?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: BlockContent;
  summary?: BlockContent;
  location?: string;
  skills?: Array<string>;
  social?: {
    github?: string;
    linkedin?: string;
    twitter?: string;
    youtube?: string;
    email?: string;
  };
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | Geopoint
  | Slug
  | SanityImageAssetReference
  | AuthorReference
  | Article
  | BlockContent
  | WorkExperience
  | Project
  | Education
  | Author
  | SanityImageAsset;

// Source: src/sanity/lib/queries.ts
// Variable: AUTHOR_QUERY
// Query: *[_type == "author"][0] {      _id,      name,      initials,      avatar {        asset-> {          url        }      },      description,      summary,      location,      skills,      social {        github,        linkedin,        twitter,        youtube,        email      }    }
export type AUTHOR_QUERY_RESULT = {
  _id: string;
  name: string | null;
  initials: string | null;
  avatar: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  description: BlockContent | null;
  summary: BlockContent | null;
  location: string | null;
  skills: Array<string> | null;
  social: {
    github: string | null;
    linkedin: string | null;
    twitter: string | null;
    youtube: string | null;
    email: string | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: WORK_QUERY
// Query: *[_type == "workExperience"] | order(startDate desc) {      _id,      company,      title,      logo {        asset-> {          url        }      },      location,      startDate,      endDate,      description,      url    }
export type WORK_QUERY_RESULT = Array<{
  _id: string;
  company: string | null;
  title: string | null;
  logo: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  location: string | null;
  startDate: string | null;
  endDate: string | null;
  description: BlockContent | null;
  url: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: EDUCATION_QUERY
// Query: *[_type == "education"] | order(startDate desc) {      _id,      school,      degree,      logo {        asset-> {          url        }      },      startDate,      endDate,      url    }
export type EDUCATION_QUERY_RESULT = Array<{
  _id: string;
  school: string | null;
  degree: string | null;
  logo: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  startDate: string | null;
  endDate: string | null;
  url: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(startDate desc) {      _id,      title,      slug,      description,      startDate,      endDate,      technologies,      image {        asset-> {          url        }      },      video,      links[] {        title,        url,        type      },      featured    }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: BlockContent | null;
  startDate: string | null;
  endDate: string | null;
  technologies: Array<string> | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  video: string | null;
  links: Array<{
    title: string | null;
    url: string | null;
    type: string | null;
  }> | null;
  featured: boolean | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {      _id,      title,      slug,      description,      longDescription,      startDate,      endDate,      technologies,      image {        asset-> {          url        }      },      gallery[] {        asset-> {          url        }      },      video,      demoUrl,      links[] {        title,        url,        type      },      featured    }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: BlockContent | null;
  longDescription: BlockContent | null;
  startDate: string | null;
  endDate: string | null;
  technologies: Array<string> | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  gallery: Array<{
    asset: {
      url: string | null;
    } | null;
  }> | null;
  video: string | null;
  demoUrl: string | null;
  links: Array<{
    title: string | null;
    url: string | null;
    type: string | null;
  }> | null;
  featured: boolean | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ARTICLES_QUERY
// Query: *[_type == "article"] | order(publishedAt desc) {      _id,      title,      slug,      excerpt,      coverImage {        asset-> {          url        }      },      author-> {        name      },      categories,      publishedAt,      featured    }
export type ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  author: {
    name: string | null;
  } | null;
  categories: Array<string> | null;
  publishedAt: string | null;
  featured: boolean | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: FEATURED_ARTICLES_QUERY
// Query: *[_type == "article" && featured == true] | order(publishedAt desc)[0...3] {      _id,      title,      slug,      excerpt,      coverImage {        asset-> {          url        }      },      author-> {        name      },      categories,      publishedAt,      featured    }
export type FEATURED_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  author: {
    name: string | null;
  } | null;
  categories: Array<string> | null;
  publishedAt: string | null;
  featured: true;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ARTICLE_BY_SLUG_QUERY
// Query: *[_type == "article" && slug.current == $slug][0] {      _id,      title,      slug,      excerpt,      coverImage {        asset-> {          url        }      },      content,      author-> {        name,        avatar {          asset-> {            url          }        }      },      categories,      publishedAt,      featured    }
export type ARTICLE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  content: BlockContent | null;
  author: {
    name: string | null;
    avatar: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
  categories: Array<string> | null;
  publishedAt: string | null;
  featured: boolean | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n    *[_type == "author"][0] {\n      _id,\n      name,\n      initials,\n      avatar {\n        asset-> {\n          url\n        }\n      },\n      description,\n      summary,\n      location,\n      skills,\n      social {\n        github,\n        linkedin,\n        twitter,\n        youtube,\n        email\n      }\n    }\n  ': AUTHOR_QUERY_RESULT;
    '\n    *[_type == "workExperience"] | order(startDate desc) {\n      _id,\n      company,\n      title,\n      logo {\n        asset-> {\n          url\n        }\n      },\n      location,\n      startDate,\n      endDate,\n      description,\n      url\n    }\n  ': WORK_QUERY_RESULT;
    '\n    *[_type == "education"] | order(startDate desc) {\n      _id,\n      school,\n      degree,\n      logo {\n        asset-> {\n          url\n        }\n      },\n      startDate,\n      endDate,\n      url\n    }\n  ': EDUCATION_QUERY_RESULT;
    '\n    *[_type == "project"] | order(startDate desc) {\n      _id,\n      title,\n      slug,\n      description,\n      startDate,\n      endDate,\n      technologies,\n      image {\n        asset-> {\n          url\n        }\n      },\n      video,\n      links[] {\n        title,\n        url,\n        type\n      },\n      featured\n    }\n  ': PROJECTS_QUERY_RESULT;
    '\n    *[_type == "project" && slug.current == $slug][0] {\n      _id,\n      title,\n      slug,\n      description,\n      longDescription,\n      startDate,\n      endDate,\n      technologies,\n      image {\n        asset-> {\n          url\n        }\n      },\n      gallery[] {\n        asset-> {\n          url\n        }\n      },\n      video,\n      demoUrl,\n      links[] {\n        title,\n        url,\n        type\n      },\n      featured\n    }\n  ': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n    *[_type == "article"] | order(publishedAt desc) {\n      _id,\n      title,\n      slug,\n      excerpt,\n      coverImage {\n        asset-> {\n          url\n        }\n      },\n      author-> {\n        name\n      },\n      categories,\n      publishedAt,\n      featured\n    }\n  ': ARTICLES_QUERY_RESULT;
    '\n    *[_type == "article" && featured == true] | order(publishedAt desc)[0...3] {\n      _id,\n      title,\n      slug,\n      excerpt,\n      coverImage {\n        asset-> {\n          url\n        }\n      },\n      author-> {\n        name\n      },\n      categories,\n      publishedAt,\n      featured\n    }\n  ': FEATURED_ARTICLES_QUERY_RESULT;
    '\n    *[_type == "article" && slug.current == $slug][0] {\n      _id,\n      title,\n      slug,\n      excerpt,\n      coverImage {\n        asset-> {\n          url\n        }\n      },\n      content,\n      author-> {\n        name,\n        avatar {\n          asset-> {\n            url\n          }\n        }\n      },\n      categories,\n      publishedAt,\n      featured\n    }\n  ': ARTICLE_BY_SLUG_QUERY_RESULT;
  }
}
